<?php
$z[0]=Array("channel","\r\n          <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n          ",279,403);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['typeid']="2";
$z[1]=Array("channel","\r\n          <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n          ",534,658);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['typeid']="4";
$z[2]=Array("channel","\r\n          <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n          ",789,913);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['typeid']="5";
$z[3]=Array("global","",1051,1083);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1252,1284);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1389,1415);
$z[5][4]=array();
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",1431,1455);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";

?>